# Generated by Django 5.0.1 on 2024-01-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_employee_user'),
        ('common', '0009_alter_url_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companywebsite',
            name='url',
        ),
        migrations.AddField(
            model_name='companywebsite',
            name='url',
            field=models.ManyToManyField(related_name='company_website', to='common.url'),
        ),
    ]
