# Generated by Django 5.0.1 on 2024-02-12 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_companywebsite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywebsite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_website', to='administration.company'),
        ),
        migrations.RemoveField(
            model_name='companywebsite',
            name='url',
        ),
        migrations.AddField(
            model_name='companywebsite',
            name='url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
