# Generated by Django 5.0.1 on 2024-02-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_companywebsite_company_and_more'),
        ('common', '0011_remove_pictures_user_alter_path_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywebsite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_websites', to='administration.company'),
        ),
        migrations.RemoveField(
            model_name='companywebsite',
            name='url',
        ),
        migrations.AddField(
            model_name='companywebsite',
            name='url',
            field=models.ManyToManyField(related_name='company_websites', to='common.path'),
        ),
    ]
