# Generated by Django 5.0.1 on 2024-01-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename__priority_personplace_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='application',
            field=models.CharField(choices=[('contenttypes', 'contenttypes'), ('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('sessions', 'sessions'), ('messages', 'messages'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='classification',
            name='app',
            field=models.CharField(blank=True, choices=[('contenttypes', 'contenttypes'), ('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('sessions', 'sessions'), ('messages', 'messages'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50, null=True, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='application',
            field=models.CharField(choices=[('contenttypes', 'contenttypes'), ('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('sessions', 'sessions'), ('messages', 'messages'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettingspic',
            name='app',
            field=models.CharField(blank=True, choices=[('contenttypes', 'contenttypes'), ('administration', 'administration'), ('food', 'food'), ('nursing', 'nursing'), ('shopping', 'shopping'), ('tourism', 'tourism'), ('accommodation', 'accommodation'), ('transportation', 'transportation'), ('treatment', 'treatment'), ('common', 'common'), ('communication', 'communication'), ('financialhub', 'financialhub'), ('django_extensions', 'django_extensions'), ('rest_framework', 'rest_framework'), ('rest_framework_simplejwt', 'rest_framework_simplejwt'), ('sslserver', 'sslserver'), ('corsheaders', 'corsheaders'), ('token_blacklist', 'token_blacklist'), ('admin', 'admin'), ('auth', 'auth'), ('sessions', 'sessions'), ('messages', 'messages'), ('staticfiles', 'staticfiles'), ('django_user_agents', 'django_user_agents')], max_length=50, null=True),
        ),
    ]
