# Generated by Django 5.0.1 on 2024-01-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
    ]
