# Generated by Django 5.0.1 on 2024-02-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_path_delete_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
        migrations.AlterField(
            model_name='path',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Website Address'),
        ),
    ]
