# Generated by Django 5.0.1 on 2024-02-17 11:35

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_pictures_user_alter_path_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.models.ActiveManagerUser()),
            ],
        ),
    ]
